Chèn thư viện tensorflow và numpy

In [ ]:
import tensorflow as tf
import numpy as np

Tensor 0 - Chiều

In [ ]:
# This will be an int32 tensor by default;
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


Ví dụ: Tạo một tensor scalar với kiểu dữ liệu là int16 va float 32 và string

In [ ]:
# This will be an int32 tensor by default;
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


Tensor 1 - Chiều. Ví dụ: Tạo tensor 1 - Chiều gồm 3 phần tử

In [ ]:
# We make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


Tensor 2 - chiều (ma trận)

In [ ]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


Tensor n-chiều (nhiều trục)

In [ ]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


Thuộc tính của tensor: Một tensor gồm có 3 thuộc tính: label (name), dimension (shape) và data type (dtype)

In [ ]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


Tạo tensor tự động gán giá trị 0 ban đầu.

In [ ]:
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


Tạo tensor tự động gán giá trị 1 ban đầu.

In [ ]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


Tạo tensor tự động với giá trị bất kỳ

In [ ]:
t_1 = tf.fill([3], 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


Tạo tensor 1-chiều vớ hàm linspace

In [ ]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


Tạo tensor 1-chiều với hàm range

In [ ]:
# Cách 1: Định nghĩa rõ ràng điểm bắt đầu (start=3.0) và điểm kết thúc (limit=7.0)
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

# Cách 2: Nếu chỉ truyền một giá trị số thực đầu tiên, TensorFlow sẽ hiểu đó là điểm kết thúc (limit=3.0)
# và tự động lấy điểm bắt đầu mặc định (start=0.0)
range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


Tạo tensor với giá trị ngẫu nhiên

Hàm tf.random.normal (Khởi tạo theo phân phối chuẩn)

In [ ]:
# Ví dụ 1: Tạo tensor ngẫu nhiên phân phối chuẩn gồm 5 phần tử (Mảng 1 chiều)
range_tensor = tf.random.normal([5])
print(range_tensor)

# Ví dụ 2: Tạo ma trận ngẫu nhiên phân phối chuẩn kích thước 3x3
range_tensor = tf.random.normal([3, 3])
print(range_tensor)

tf.Tensor([1.16215    1.1389076  0.25344074 1.6097684  1.4536903 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 1.1364757  -1.6134845   1.1946112 ]
 [-0.7997615   0.412218   -0.3539302 ]
 [ 0.51487875  0.507109    1.0174426 ]], shape=(3, 3), dtype=float32)


2. Hàm tf.random.truncated_normal (Khởi tạo theo phân phối chuẩn cắt cụt)

In [ ]:
# Ví dụ 1: Tạo tensor phân phối chuẩn cắt cụt gồm 5 phần tử
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

# Ví dụ 2: Tạo ma trận ngẫu nhiên kích thước 3x2
range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

# Ví dụ 3: Tạo khối tensor 3 chiều kích thước 3x2x2
range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

tf.Tensor([-0.49206612  0.45967397  0.1324512  -0.9785766  -0.9566144 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.7170122  -0.08987646]
 [-0.18206826  0.89149755]
 [-0.09479269 -0.20093612]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[ 0.1202236  -1.1212825 ]
  [ 1.0505044   1.1124122 ]]

 [[ 0.7888535   1.1665854 ]
  [-0.2058691  -0.87210816]]

 [[ 0.14425687  1.889017  ]
  [ 0.58573186 -0.12138677]]], shape=(3, 2, 2), dtype=float32)


3. Hàm tf.random.uniform (Khởi tạo theo phân phối đều)

In [ ]:
# Ví dụ 1: Tạo tensor 5 phần tử nằm trong khoảng từ 10 đến 20
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

# Ví dụ 2: Tạo ma trận kích thước 3x2 nằm trong khoảng từ 10 đến 20
range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

# Ví dụ 3: Tạo khối tensor 3 chiều kích thước 3x2x5 nằm trong khoảng từ 10 đến 20
range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor([13.156728 11.304635 19.561565 11.421823 19.649029], shape=(5,), dtype=float32)
tf.Tensor(
[[15.821515 16.65982 ]
 [18.332405 16.900387]
 [14.388941 14.462044]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[15.451376 19.965008 11.405682 17.252256 19.177425]
  [16.561867 15.872631 14.013701 11.645449 14.021138]]

 [[16.051203 14.375486 11.053163 10.389824 12.945173]
  [13.904151 15.744276 15.302787 12.264866 16.352036]]

 [[10.197744 10.769544 16.348015 16.49119  18.441734]
  [17.250242 13.019987 16.871008 14.569472 15.044706]]], shape=(3, 2, 5), dtype=float32)


4. Hàm tf.random.shuffle (Xáo trộn ngẫu nhiên vị trí phần tử)

In [ ]:
# Tạo một tensor ngẫu nhiên phân phối đều trước
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print("Tensor gốc ban đầu:")
print(range_tensor)

# Tiến hành xáo trộn ngẫu nhiên vị trí các hàng
shuffled_tensor = tf.random.shuffle(range_tensor)
print("\nTensor sau khi dùng shuffle để xáo trộn:")
print(shuffled_tensor)

Tensor gốc ban đầu:
tf.Tensor([14.8166485 10.406256  10.926435  12.55795   10.008079 ], shape=(5,), dtype=float32)

Tensor sau khi dùng shuffle để xáo trộn:
tf.Tensor([10.926435  10.406256  10.008079  12.55795   14.8166485], shape=(5,), dtype=float32)


tf.random.set_seed(seed)

In [ ]:
tf.random.set_seed(42)  # Cố định lõi ngẫu nhiên cho toàn đồ thị tính toán

Chuyển đổi kiểu dữ liệu

In [ ]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)

# Ép kiểu từ float32 sang int32 (Phần thập phân .9 sẽ bị chặt cụt thành 3)
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


Các phép toán trong tensorflow: Tính căn bậc 2 của một tensor scalar

In [ ]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


Các phép toán trong tensorflow: Cộng 2 tensor

In [ ]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

# Cách 1: Sử dụng hàm API chính thức tf.add
c = tf.add(a, b)

# Cách 2: Sử dụng toán tử toán học dấu cộng thông thường (+) nhờ cơ chế Operator Overloading
d = a + b

print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


Các phép toán trong tensorflow: Nhân 2 tensor

In [ ]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

# Cách 1: Sử dụng hàm API chính thức tf.multiply
c = tf.multiply(a, b)

# Cách 2: Sử dụng toán tử dấu sao (*) nhờ cơ chế Operator Overloading
d = a * b

print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [ ]:
a = tf.constant([6. , 6. , 6.])
b = tf.constant([4. , 4. , 4.])
c = tf.constant([3. , 3. , 3.])

d = tf.add(a, b)                  # Cộng 2 tensor element-wise
e = tf.add_n([a, b, c])           # Cộng nhiều tensor cùng kích thước lại với nhau
f = tf.subtract(a, b)             # Phép trừ element-wise
g = tf.multiply(a, b)             # Phép nhân element-wise
h = tf.divide(a, b)               # Phép chia element-wise
i = tf.scalar_mul(3, a)           # Nhân một số vô hướng (scalar) với tất cả phần tử của tensor
j = tf.math.reciprocal(a)         # Tính nghịch đảo của từng phần tử (1 / x)
k = tf.math.mod(a, b)             # Phép chia lấy phần dư element-wise
l = tf.negative(a)                # Đổi dấu tất cả phần tử (nhân với -1)

print(i)
print(l)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


In [ ]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])

r1 = tf.round(t)         # Làm tròn đến số nguyên gần nhất (nửa khoảng làm tròn về số chẵn gần nhất)
r2 = tf.math.rint(t)    # Làm tròn đến số nguyên gần nhất (tương tự tf.round)
r3 = tf.math.ceil(t)    # Làm tròn lên (Tìm số nguyên nhỏ nhất lớn hơn hoặc bằng x)
r4 = tf.math.floor(t)   # Làm tròn xuống (Tìm số nguyên lớn nhất nhỏ hơn hoặc bằng x)

print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


Bài tập: sinh viên tìm hiểu các hàm trên qua vd

In [ ]:
import tensorflow as tf

# KHỞI TẠO CÁC TENSOR BAN ĐẦU
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

# 1. TÍCH CO TENSOR (TENSOR DOT PRODUCT)
# axes=0: Nhân tensor outer product (tích ngoài), tạo ra ma trận kết hợp bậc cao hơn.
dot_x = tf.tensordot(t1, t2, 0)
# axes=1: Nhân vô hướng hai vector (Dot Product thông thường) -> Kết quả: 4*3 + 3*2 + 2*1 = 20.0
dot_y = tf.tensordot(t1, t2, 1)

# LỆNH IN THỬ KIỂM TRA DỮ LIỆU GỐC
print(t1)
print(t2)
print(t3)
print(t4)

# 2. TÍCH CÓ HƯỚNG GIỮA HAI VECTOR (CROSS PRODUCT)
# Chỉ áp dụng cho vector 3 chiều, trả về một vector mới vuông góc với mặt phẳng chứa t1 và t2.
cross = tf.linalg.cross(t1, t2)

# 3. PHÉP NHÂN MA TRẬN ĐẠI SỐ TUYẾN TÍNH (MATRIX MULTIPLICATION)
# Nhân hàng của t3 (2x3) với cột của t4 (3x2) để tạo ra một ma trận mới có kích thước (2x2).
mm = tf.matmul(t3, t4)

# 4. RÚT TRÍCH ĐƯỜNG CHÉO CHÍNH (DIAGONAL)
# Lấy ra các phần tử nằm trên đường chéo chính của ma trận t3.
d = tf.linalg.diag(t3)

# 5. TÍNH VẾT CỦA MA TRẬN (TRACE)
# Tổng của các phần tử nằm trên đường chéo chính của ma trận.
trace = tf.linalg.trace(t3)

# 6. PHÉP CHUYỂN VỊ MA TRẬN (TRANSPOSE)
# Biến các hàng của ma trận t3 thành các cột của ma trận mới (kích thước chuyển từ 2x3 sang 3x2).
trans = tf.transpose(t3)

# 7. KHỞI TẠO MA TRẬN ĐƠN VỊ (IDENTITY MATRIX)
# Tạo một ma trận kích thước 5x5 chứa toàn số 0, ngoại trừ đường chéo chính chứa toàn số 1.
eye = tf.eye(5, 5)

# ĐOẠN XUẤT KẾT QUẢ RA MÀN HÌNH THEO HÌNH ẢNH
print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


Để khai báo một biến trong tensorflow

In [ ]:
import tensorflow as tf

# 1. Khởi tạo một biến số thực bậc 0 (Scalar)
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

# 2. Khởi tạo một biến dạng mảng gồm 2 phần tử số nguyên (Vector bậc 1)
diem = tf.Variable([5, 9])
print(diem)

# 3. Xem các thuộc tính cốt lõi của biến
print('Shape', diem.shape)       # Xem cấu trúc hình học (Kích thước các chiều)
print('Dtype', diem.dtype)       # Xem kiểu dữ liệu của các phần tử bên trong
print('numpy:', diem.numpy())    # Chuyển đổi giá trị của Tensor về dạng mảng NumPy thông thường

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]


Phép gán giá trị cho tensor

In [ ]:
import tensorflow as tf

# KHỞI TẠO BIẾN BAN ĐẦU
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)

# 1. Hàm .assign() -> Gán/Thay thế bằng một giá trị hoàn toàn mới
# Biến 'diem' chuyển từ [5, 9] thành [8, 10]
diem.assign([8, 10])
print(diem)

# 2. Hàm .assign_add() -> Phép toán cộng tích lũy (Tương đương toán tử +=)
# Lấy giá trị hiện tại [8, 10] cộng thêm [1, 1] -> Kết quả mới: [9, 11]
diem.assign_add([1, 1])
print(diem)

# 3. Hàm .assign_sub() -> Phép toán trừ tích lũy (Tương đương toán tử -=)
# Lấy giá trị hiện tại [9, 11] trừ đi [5, 5] -> Kết quả cuối cùng: [4, 6]
diem.assign_sub([5, 5])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


In [ ]:
import tensorflow as tf

# Định nghĩa một hàm Python thông thường (Chạy ở chế độ Eager Execution)
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# CHUYỂN ĐỔI SANG GRAPH: Bọc hàm Python thông thường lại thành một TensorFlow Function
# Lúc này, TensorFlow sẽ biên dịch tĩnh các phép toán bên trong thành một Đồ thị tính toán (Computation Graph)
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Khởi tạo các Tensor kiểm thử
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

# Gọi hàm chạy ở chế độ thông thường (Eager Mode)
orig_value = a_regular_function(x1, y1, b1).numpy()

# Gọi hàm đã được tối ưu hóa bằng Graph (Graph Mode)
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

# Xuất kết quả nghiệm thu (Cả hai chế độ đều cho ra cùng một đáp án số học là 12.0)
print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


In [ ]:
@tf.function
def my_fast_function(x, y, b):
    return tf.matmul(x, y) + b

In [ ]:
import tensorflow as tf

# Định nghĩa một hàm Python thông thường (Không có @tf.function)
def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Sử dụng decorator @tf.function để biến hàm 'outer_function' thành một TensorFlow Graph Function
@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)

    # Hàm outer gọi hàm inner bên trong nó
    return inner_function(x, y, b)

# Gọi thực thi hàm với một Tensor đầu vào
# Dòng chú thích trong hình: Note that the callable will create a graph that includes `inner_function` as well as `outer_function`.
rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]


3.18. Modeles, layers và models

Ví dụ tạo lớp SimpleModule xử lý tensor scalar (Layer)

In [ ]:
import tensorflow as tf

# Tạo một lớp Module tùy biến bằng cách kế thừa tf.Module
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

        # 1. Biến có thể huấn luyện (Trainable Variable - Trọng số học tập chuẩn)
        self.a_variable = tf.Variable(5.0, name="train_me")

        # 2. Biến đóng băng / cố định (Non-trainable Variable - Không tham gia huấn luyện)
        # Đặt thuộc tính trainable=False để thuật toán Gradient Descent bỏ qua không cập nhật biến này
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

    def __call__(self, x):
        # Định nghĩa phép toán Forward Pass (Lan truyền tiến): y = a * x + b
        return self.a_variable * x + self.non_trainable_variable

# Khởi tạo một đối tượng từ lớp vừa định nghĩa
simple_module = SimpleModule(name="simple")

# Gọi thực thi tính toán Forward với đầu vào x = 5.0 -> Kết quả: 5.0 * 5.0 + 5.0 = 30.0
rs = simple_module(tf.constant(5.0))
print(rs)

# TRÍCH XUẤT QUẢN LÝ BIẾN CỦA TENSORFLOW
print('Train variables', simple_module.trainable_variables)
print('All variables', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)


Ví dụ tạo model với nhiều tầng layer

In [ ]:
import tensorflow as tf

# 1. Định nghĩa tầng liên kết đầy đủ (Dense Layer / Fully Connected Layer)
class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        # Khởi tạo ma trận trọng số w ngẫu nhiên theo phân phối chuẩn
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name='w')
        # Khởi tạo độ lệch b chứa toàn số 0
        self.b = tf.Variable(tf.zeros([out_features]), name='b')

    def __call__(self, x):
        # Tính Forward Pass: y = (x * w) + b
        y = tf.matmul(x, self.w) + self.b
        # Đi qua hàm kích hoạt ReLU để khử tuyến tính (Giữ lại số dương, ép số âm về 0)
        return tf.nn.relu(y)

# 2. Kết hợp các tầng đơn lẻ thành một chuỗi mạng nơ-ron (Sequential Model)
class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        # Tầng ẩn 1: Nhận vào 3 đặc trưng, trích xuất ra 3 đặc trưng
        self.dense_1 = Dense(in_features=3, out_features=3)
        # Tầng đầu ra 2: Nhận vào 3 đặc trưng từ tầng 1, đưa ra 2 kết quả dự đoán cuối cùng
        self.dense_2 = Dense(in_features=3, out_features=2)

    def __call__(self, x):
        # Dữ liệu đi tuần tự qua tầng 1 rồi ném kết quả vào tầng 2
        x = self.dense_1(x)
        return self.dense_2(x)

# Khởi tạo mô hình
# Dòng chú thích: You have made a model!
my_model = SequentialModule(name="the_model")

# Gọi mô hình với dữ liệu đầu vào giả lập là một vector kích thước (1, 3)
# Dòng chú thích: Call it, with random results
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

Model results: tf.Tensor([[0.        1.2104536]], shape=(1, 2), dtype=float32)


3.19.1: Lưu checkpoint

In [ ]:
import tensorflow as tf

# 1. Định nghĩa đường dẫn/tên file để lưu trữ checkpoint
chkp_path = "my_checkpoint"

# 2. Khởi tạo một đối tượng Checkpoint và gắn mô hình của cậu vào tham số quản lý
# (Ở đây 'my_model' chính là đối tượng mạng SequentialModule cậu đã tạo ở câu trước)
checkpoint = tf.train.Checkpoint(model=my_model)

# 3. Ghi/Lưu toàn bộ giá trị trọng số (w) và bias (b) hiện tại xuống đĩa cứng
checkpoint.write(chkp_path)

'my_checkpoint'

Phục hồi checkpoint

In [ ]:
import tensorflow as tf

# 1. Khởi tạo một đối tượng mô hình hoàn toàn mới (Trọng số lúc này đang là ngẫu nhiên)
new_model = SequentialModule()

# 2. Tạo một đối tượng Checkpoint mới và gắn mô hình mới vào để quản lý
new_checkpoint = tf.train.Checkpoint(model=new_model)

# 3. Nạp/Khôi phục lại toàn bộ trọng số cũ từ file "my_checkpoint" đè lên mô hình mới
new_checkpoint.restore("my_checkpoint")

# 4. Kiểm tra độ đồng nhất: Dự báo với cùng một đầu vào [[2.0, 2.0, 2.0]]
# Dòng chú thích: Should be the same result as above
print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[0.        1.2104536]], shape=(1, 2), dtype=float32)


1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [ ]:
import tensorflow as tf

# Tạo tensor kích thước [2, 3] chứa toàn số 0
t_zero = tf.zeros([2, 3])

print(t_zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


2. Cho X = [[1, 2, 3], [4, 5, 6]], hãy tạo tensor có kích thước và dtype như X với các phần tử được
gán 0

Cách 1: Sử dụng hàm tf.zeros_like (Ngắn gọn và tối ưu nhất)

In [ ]:
import tensorflow as tf

# Khởi tạo ma trận X ban đầu
X = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

# Tạo tensor chứa toàn số 0 có cùng shape và dtype với X
X_zero = tf.zeros_like(X)

print(X_zero)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


Cách 2: Sử dụng thuộc tính .shape và .dtype của X

In [ ]:
import tensorflow as tf

X = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

# Lấy thủ công thông tin kích thước và kiểu dữ liệu của X truyền vào tf.zeros
X_zero_manual = tf.zeros(shape=X.shape, dtype=X.dtype)

print(X_zero_manual)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


3. Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5

Cách 1: Sử dụng hàm tf.fill

In [ ]:
import tensorflow as tf

# Tạo tensor kích thước [3, 2] chứa toàn số 5
t_five = tf.fill([3, 2], 5)

print(t_five)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


Cách 2: Sử dụng toán tử nhân với tf.ones

In [ ]:
import tensorflow as tf

# Tạo ma trận toàn số 1 rồi nhân với 5
t_five_alt = tf.ones([3, 2], dtype=tf.int32) * 5

print(t_five_alt)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [ ]:
import tensorflow as tf

# Tạo tensor 1-chiều gồm 50 phần tử chẵn cách đều nhau trong khoảng [6.0, 10.0]
t_even = tf.linspace(6.0, 10.0, 50)

print(t_even)

tf.Tensor(
[ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ], shape=(50,), dtype=float32)


5. Tạo một tensor 1-chiều có giá trị như [10, 12, 14, …, 100]

In [ ]:
import tensorflow as tf

# Tạo tensor 1-chiều chạy từ 10 đến 100 với bước nhảy là 2
# Lưu ý: Điểm kết thúc (limit) phải đặt là 101 để chuỗi lấy được cả số 100
t_range = tf.range(start=10, limit=101, delta=2)

print(t_range)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


6. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối normal với mean=0,
standard deviation = 2

In [ ]:
import tensorflow as tf

# Tạo tensor ngẫu nhiên phân phối chuẩn kích thước [3, 2]
# Định rõ mean = 0.0 và độ lệch chuẩn (stddev) = 2.0
t_random_normal = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)

print(t_random_normal)

tf.Tensor(
[[ 0.01849299 -1.3241255 ]
 [-1.4820538   2.3970523 ]
 [ 1.7272416   0.78515124]], shape=(3, 2), dtype=float32)


7. Tạo một tensor kích thước [3, 2] có giá trị ngẫu nhiên theo phân phối uniform trong phạm vi
[0, 2]

In [ ]:
import tensorflow as tf

# Tạo tensor ngẫu nhiên phân phối đều kích thước [3, 2]
# Định rõ giá trị nhỏ nhất (minval) = 0.0 và lớn nhất (maxval) = 2.0
t_random_uniform = tf.random.uniform(shape=[3, 2], minval=0.0, maxval=2.0)

print(t_random_uniform)

tf.Tensor(
[[1.9166367  0.03361678]
 [0.631207   0.32026315]
 [1.4297404  1.5785842 ]], shape=(3, 2), dtype=float32)


8. Cho tensor X = [[1, 2], [3, 4], [5, 6]]. Hãy shuffle X theo chiều thứ nhất (sử dụng
random_shuffle)

In [ ]:
import tensorflow as tf

# Khởi tạo ma trận X ban đầu kích thước [3, 2]
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Xáo trộn ngẫu nhiên X theo chiều thứ nhất (trục các hàng)
shuffled_X = tf.random.shuffle(X)

print(shuffled_X)

tf.Tensor(
[[3 4]
 [5 6]
 [1 2]], shape=(3, 2), dtype=int32)


9. Hãy tạo ngẫu nhiên tensor kích thước (10, 10, 3). Cắt thành tensor có kích thước (5, 5, 3) (sử
dụng random_crop)

In [ ]:
import tensorflow as tf

# 1. Tạo ngẫu nhiên một tensor kích thước (10, 10, 3)
# Ở đây tớ dùng phân phối đều (Uniform) trong khoảng [0, 255] để giả lập một tấm ảnh màu RGB
original_tensor = tf.random.uniform(shape=[10, 10, 3], minval=0, maxval=255, dtype=tf.int32)

# 2. Thực hiện cắt ngẫu nhiên về kích thước (5, 5, 3)
# Tham số size nhận vào một mảng định hình cấu trúc kích thước mục tiêu muốn giữ lại
cropped_tensor = tf.image.random_crop(original_tensor, size=[5, 5, 3])

print("Kích thước tensor gốc:", original_tensor.shape)
print("Kích thước tensor sau khi cắt:", cropped_tensor.shape)

Kích thước tensor gốc: (10, 10, 3)
Kích thước tensor sau khi cắt: (5, 5, 3)
