In [1]:
pip install numpy

Array 1 chiều

In [29]:
import numpy as np
#Cách 1
#tạo list
my_list = [1,9,15,39]
print('Pyton list:', my_list)
#chuyển list -> Numpy array
my_numpy_array = np.array(my_list)
print('Cách 1')
print('Numpy array:', my_numpy_array)

#Cách 2
a = np.array([1,9,15,39])
print('Cách 2')
print(a)

Pyton list: [1, 9, 15, 39]
Cách 1
Numpy array: [ 1  9 15 39]
Cách 2
[ 1  9 15 39]


Array 2 chiều

In [8]:
c= np.array([(1,2,3),
             (4,5,6)
             ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


Array 3 chiều

In [7]:
d = np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
print(d)
print(d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


Tạo array với giá trị ban đầu là 0 hay 1

In [13]:
e = np.zeros((2,3))
f = np.ones((3,3))
g = np.zeros((2,2))
print('Zero matrix:\n', e)
print('One matrix\n', f)
print('Zero matrix\n', g)

Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Zero matrix
 [[0. 0.]
 [0. 0.]]


Reshape thay đổi kích thước ma trận

In [20]:
e = np.array([(1,2,3),
             (4,5,6)
             ])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
l = np.array([[[1,2,3], [4,5,6]],
             [[7,8,9], [10,11,12]]
             ])
print('Ma trận và chiều ban đầu')
print(l)
print(l.shape) # số chiều của ma trận ban đầu
print('Thay đổi chiều ma trận')
h = l.reshape(3,4)
print('reshape (3,4)\n', h)
j = l.reshape(3,2,2)
print('reshape (3,2,2)\n', h)
k = l.reshape(2,3,2)
print('reshape (2,3,2)\n', h)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
Ma trận và chiều ban đầu
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
Thay đổi chiều ma trận
reshape (3,4)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape (3,2,2)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape (2,3,2)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Platten chuyển array nhiều về 1 chiều

In [21]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print("Flatten e:", f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
j = g.flatten()
print("Flatten g:", j)

Flatten e: [1. 2. 3. 4. 5. 6.]
Flatten g: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


Thêm dòng/cột dữ liệu với hstack và vstack

In [22]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

# Ghép nối theo chiều ngang
h_stack = np.hstack((f, g))
print('Horizontal Append:\n', h_stack)

# Ghép nối theo chiều dọc
v_stack = np.vstack((f, g))
print('Vertical Append:\n', v_stack)

Horizontal Append:
 [1. 2. 3. 4. 5. 6.]
Vertical Append:
 [[1. 2. 3.]
 [4. 5. 6.]]


Sinh mảng số ngẫu nhiên (Nguyên và Thực)

In [23]:
# Sinh mảng số nguyên ngẫu nhiên nhỏ hơn 100
a = np.random.randint(100, size=(5,))
print('Random 1-D int array:\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D int array:\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D int array:\n', c)

# Sinh mảng số thực ngẫu nhiên trong khoảng [0, 1]
rand_1d = np.random.rand(5)
print('\nRandom 1-D float array:\n', rand_1d)

rand_2d = np.random.rand(3, 4)
print('Random 2-D float array:\n', rand_2d)

rand_3d = np.random.rand(3, 4, 3)
print('Random 3-D float array:\n', rand_3d)

Random 1-D int array:
 [91  3 51 82 73]
Random 2-D int array:
 [[10  0 38 10]
 [52 51 23 33]
 [79  6 82 14]]
Random 3-D int array:
 [[[39 41 77]
  [89 79 64]
  [31 18 63]
  [88 83  3]]

 [[ 6 86 59]
  [ 2 12 88]
  [69  7 83]
  [24 16 59]]

 [[24  7 85]
  [ 8 96 47]
  [90 44 81]
  [28 48 66]]]

Random 1-D float array:
 [0.5519058  0.27387783 0.07474802 0.06809645 0.18185998]
Random 2-D float array:
 [[0.32457964 0.32550598 0.8391987  0.96949897]
 [0.60093612 0.54580798 0.31766121 0.11278932]
 [0.10974444 0.40219145 0.24529453 0.09404082]]
Random 3-D float array:
 [[[0.73913714 0.98890298 0.31535852]
  [0.85458317 0.52262104 0.52937371]
  [0.78033055 0.39562355 0.82422656]
  [0.39551183 0.28381115 0.99106477]]

 [[0.81596521 0.69770339 0.29288176]
  [0.96765409 0.38717893 0.45877462]
  [0.37833789 0.68115845 0.3855882 ]
  [0.21601569 0.91649595 0.87252056]]

 [[0.79592077 0.57921174 0.7793793 ]
  [0.78535703 0.03437702 0.33877933]
  [0.18233325 0.54160253 0.27464052]
  [0.70297791 0.1224

Sinh mảng ngẫu nhiên theo phân phối chuẩn Gaussian

In [24]:
# loc: giá trị trung tâm (mean), scale: độ lệch chuẩn (std), size: số phần tử
a = np.random.normal(loc=5, scale=0.5, size=10)
print(a)

[5.04341481 4.7103527  4.84884501 5.03331334 4.83933485 3.62582562
 5.28832445 4.63383093 5.13584977 4.04695402]


Sinh ngẫu nhiên giá trị từ mảng cho trước (Choice)

In [25]:
# Sinh 1 giá trị ngẫu nhiên
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print("Một giá trị ngẫu nhiên:", a)

# Sinh ma trận kích thước 3 x 5
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print("Ma trận ngẫu nhiên 3x5:\n", b)

Một giá trị ngẫu nhiên: 20
Ma trận ngẫu nhiên 3x5:
 [[ 2 16  8 14 12]
 [ 6 10 14 14 10]
 [14  8  8 14  8]]


Thay đổi giá trị của ma trận (Sự khác biệt giữa sao chép và tham chiếu)

In [26]:
# Tạo ma trận 5 x 5 toàn số 1
A = np.matrix(np.ones((5, 5)))
print('Ma trận gốc A:\n', A)

# Sử dụng np.array tạo bản sao mới (không ảnh hưởng ma trận gốc A)
B = np.array(A)
B[2] = 2
print('Thay đổi dòng 3 trên bản sao bằng np.array (A không đổi):\n', A)

# Sử dụng np.asarray tạo tham chiếu (thay đổi trực tiếp lên ma trận gốc A)
np.asarray(A)[2] = 2
print('Thay đổi dòng 3 bằng np.asarray (A bị thay đổi):\n', A)

Ma trận gốc A:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Thay đổi dòng 3 trên bản sao bằng np.array (A không đổi):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Thay đổi dòng 3 bằng np.asarray (A bị thay đổi):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Sinh dãy số theo khoảng cho trước (Arange & Linspace)

In [27]:
# Hàm arange: khởi đầu, kết thúc (không gồm n), bước nhảy
a = np.arange(1, 20)
print("Arange bước nhảy 1:\n", a)

b = np.arange(1, 20, 2)
print("Arange bước nhảy 2:\n", b)

# Hàm linspace: khởi đầu, kết thúc, số lượng phần tử được chia đều
c = np.linspace(1., 5., num=10)
print("Linspace chia đều 10 phần tử từ 1 đến 5:\n", c)

Arange bước nhảy 1:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Arange bước nhảy 2:
 [ 1  3  5  7  9 11 13 15 17 19]
Linspace chia đều 10 phần tử từ 1 đến 5:
 [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


3.10. Index và Slice (Cắt mảng và Truy xuất phần tử)

In [28]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print("Mảng gốc:\n", a)
print('Dòng đầu tiên (row 0):', a[0])
print('Dòng thứ hai (row 1):', a[1])

# Indexing & Slicing dòng/cột
print('Cột thứ hai (column 1):', a[:, 1])
print('Cột đầu tiên (column 0):', a[:, 0])
print('Phần tử tại dòng 1, cột 2 (số 6):', a[1, 2])

Mảng gốc:
 [[1 2 3]
 [4 5 6]]
Dòng đầu tiên (row 0): [1 2 3]
Dòng thứ hai (row 1): [4 5 6]
Cột thứ hai (column 1): [2 5]
Cột đầu tiên (column 0): [1 4]
Phần tử tại dòng 1, cột 2 (số 6): 6


Tìm hiểu đối tượng Series

In [30]:
import pandas as pd
# Tạo Pandas Series từ List
a = pd.Series([1., 2., 3.])
print("Series từ list:\n", a)
print('Giá trị đầu tiên:', a[0])

# Tạo Series với nhãn tùy chỉnh (Index)
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print("\nSeries có index cụ thể:\n", b)
print('Giá trị tại nhãn a:', b['a'])

# Tạo Series từ Dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print("\nSeries từ Dictionary:\n", myvar)

Series từ list:
 0    1.0
1    2.0
2    3.0
dtype: float64
Giá trị đầu tiên: 1.0

Series có index cụ thể:
 a    1.0
b    2.0
c    3.0
dtype: float64
Giá trị tại nhãn a: 1.0

Series từ Dictionary:
 day1    420
day2    380
day3    390
dtype: int64


Tạo đối tượng DataFrame (Chuyển đổi Numpy <-> Pandas)

In [31]:
# Chuyển đổi từ Numpy sang Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame chuyển từ Numpy:\n', df_h)

# Chuyển ngược từ Pandas về Numpy
numpy_h = np.array(df_h)
print('\nMảng Numpy chuyển ngược lại:\n', numpy_h)

DataFrame chuyển từ Numpy:
    0  1
0  1  2
1  3  4

Mảng Numpy chuyển ngược lại:
 [[1 2]
 [3 4]]


Tạo DataFrame kèm tên cột và hiển thị cơ bản

In [32]:
# Tạo từ dictionary kèm tên cột
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print("DataFrame từ Dictionary:\n", df_dic)

# Tạo mảng ngẫu nhiên 20 x 4 và đặt tên cột
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print("\n5 dòng đầu tiên của DataFrame ngẫu nhiên:")
print(df.head())  # in 5 dòng đầu tiên

DataFrame từ Dictionary:
     Name  Age
0   John   30
1  Smith   40

5 dòng đầu tiên của DataFrame ngẫu nhiên:
        so1       so2       so3       so4
0  0.664669 -0.471803 -0.704690 -0.159487
1  0.461084  0.723270  1.253571  0.570063
2  0.177683 -0.198331  0.511350  0.224806
3  0.271372 -2.414294 -0.518192  0.510345
4  0.430492 -0.010192  1.842523 -0.707139


Thao tác nâng cao trên DataFrame (Nối, Lọc, Xóa cột) - Từ tài liệu hình ảnh

In [33]:
# Tạo dữ liệu mẫu
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'], 'Age': [25, 30, 50]}, index=[1, 2, 3])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [28, 11]}, index=[4, 5])

# 7.1. Nối nhiều DataFrame
df_concat = pd.concat([df1, df2])
print("Sau khi nối DataFrame:\n", df_concat)

# Loại bỏ trùng lặp dựa trên cột 'Name'
df_drop_dup = df_concat.drop_duplicates(subset=['Name'])
print("\nSau khi loại bỏ trùng lặp tên:\n", df_drop_dup)

# Sắp xếp theo cột 'Age'
df_sorted = df_concat.sort_values(by='Age')
print("\nSau khi sắp xếp theo Age:\n", df_sorted)

# Đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print("\nSau khi đổi tên cột:\n", df_rename)

# Xóa bớt cột dữ liệu
df_dropped = df_concat.drop(columns=['Age'])
print("\nSau khi xóa cột Age:\n", df_dropped)

Sau khi nối DataFrame:
     Name  Age
1   John   25
2  Smith   30
3   Paul   50
4   Adam   28
5  Smith   11

Sau khi loại bỏ trùng lặp tên:
     Name  Age
1   John   25
2  Smith   30
3   Paul   50
4   Adam   28

Sau khi sắp xếp theo Age:
     Name  Age
5  Smith   11
1   John   25
4   Adam   28
2  Smith   30
3   Paul   50

Sau khi đổi tên cột:
   Surname  Age_pupil
1    John         25
2   Smith         30
3    Paul         50
4    Adam         28
5   Smith         11

Sau khi xóa cột Age:
     Name
1   John
2  Smith
3   Paul
4   Adam
5  Smith


Đọc dữ liệu từ file CSV (Cú pháp chuẩn)

In [ ]:
import os #tạo file data csv

# 1. Tạo thư mục /content/sample_data/ nếu chưa có
os.makedirs('/content/sample_data', exist_ok=True)

# 2. Định nghĩa nội dung file CSV dữ liệu mẫu
csv_content = """YearsExperience,Salary
1.1,39343
1.3,46205
1.5,37731
2.0,43525
2.2,39891
2.9,56642
3.0,60150
3.2,54445
3.2,64445
3.7,57189
3.9,63218
4.0,55794
4.0,56957
4.1,57081
4.5,61111
4.9,67938
5.1,66029
5.3,83088
5.9,81363
6.0,93940
6.8,91738
7.1,98273
7.9,101302
8.2,113812
8.7,109431
9.0,105582
9.5,116969
9.6,112635
10.3,122391
10.5,121872"""

# 3. Ghi nội dung vào file đúng đường dẫn
file_path = "/content/sample_data/salary_data.csv"
with open(file_path, "w", encoding="utf-8") as f:
    f.write(csv_content.strip())

print(f"Đã tạo file thành công tại: {file_path}")

In [37]:
# Lưu ý: Bạn cần tải tệp dữ liệu lên Colab hoặc có sẵn đường dẫn tệp thực tế để chạy lệnh này
path = "/content/sample_data/salary_data.csv"
columns = ['YearsExperience', 'Salary']

# Đọc có tùy biến tên cột
try:
    df_csv = pd.read_csv(path, skipinitialspace=True, names=columns, index_col=False)
    print(df_csv.head())
    print("Kích thước:", df_csv.shape)
except FileNotFoundError:
    print(f"Lưu ý: Bạn chưa tải tệp '{path}' lên môi trường Colab hiện tại nên hàm này tạm thời chưa xuất kết quả.")

   YearsExperience  Salary
0  YearsExperience  Salary
1              1.1   39343
2              1.3   46205
3              1.5   37731
4              2.0   43525
Kích thước: (31, 2)


Gom nhóm dữ liệu DataFrame (Groupby)

In [35]:
# Hàm Groupby kết hợp các hàm tính toán cơ bản (Mô phỏng lại ảnh mẫu Iris/Fish từ bài học)
# Tạo nhanh một DataFrame mẫu để chạy trực tiếp:
data_sample = {
    'Species': ['Bream', 'Bream', 'Roach', 'Roach', 'Pike'],
    'Weight': [242.0, 290.0, 150.0, 120.0, 500.0],
    'Length': [25.4, 26.3, 22.0, 21.0, 41.0]
}
df_fish = pd.DataFrame(data_sample)

# Thực hiện gom nhóm theo Species và tính trung bình (mean)
print("Giá trị trung bình theo loài:")
print(df_fish.groupby(['Species']).mean())

print("\nĐếm số lượng phần tử theo loài:")
print(df_fish.groupby(['Species']).count())

Giá trị trung bình theo loài:
         Weight  Length
Species                
Bream     266.0   25.85
Pike      500.0   41.00
Roach     135.0   21.50

Đếm số lượng phần tử theo loài:
         Weight  Length
Species                
Bream         2       2
Pike          1       1
Roach         2       2


In [38]:
import pandas as pd
import numpy as np

# Tạo dữ liệu mô phỏng chính xác theo hình ảnh thực hành trong bài
data_fish = {
    'Species': ['Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Roach', 'Roach', 'Pike', 'Pike'],
    'Weight': [242.0, 290.0, 340.0, 363.0, 430.0, 150.0, 120.0, 500.0, 716.0],
    'Length': [25.4, 26.3, 26.5, 29.0, 29.0, 22.0, 21.0, 41.0, 42.7],
    'Height': [11.5200, 12.4440, 12.3778, 12.7300, 12.4440, 8.9520, 8.1457, 10.7388, 11.5200],
    'Width': [4.0200, 3.8417, 4.6961, 4.4555, 5.1340, 3.2928, 3.1234, 4.4555, 5.5891]
}

df_csv = pd.DataFrame(data_fish)
print("--- DataFrame gốc ban đầu ---")
print(df_csv)

--- DataFrame gốc ban đầu ---
  Species  Weight  Length   Height   Width
0   Bream   242.0    25.4  11.5200  4.0200
1   Bream   290.0    26.3  12.4440  3.8417
2   Bream   340.0    26.5  12.3778  4.6961
3   Bream   363.0    29.0  12.7300  4.4555
4   Bream   430.0    29.0  12.4440  5.1340
5   Roach   150.0    22.0   8.9520  3.2928
6   Roach   120.0    21.0   8.1457  3.1234
7    Pike   500.0    41.0  10.7388  4.4555
8    Pike   716.0    42.7  11.5200  5.5891


In [40]:
# Gom nhóm theo Species và tính trung bình (mean) của từng loài
print("--- Giá trị trung bình của từng nhóm Loài (Species) ---")
df_mean = df_csv.groupby(['Species']).mean()
print(df_mean)

# Đếm số lượng mẫu dữ liệu thuộc mỗi loài dựa theo cột Weight
print("--- Số lượng mẫu dữ liệu của mỗi loài ---")
df_count = df_csv.groupby(['Species'])['Weight'].count()
print(df_count)

# 1. Tìm giá trị nhỏ nhất (Min) của từng loài
print("--- Giá trị nhỏ nhất (Min) theo từng loài ---")
print(df_csv.groupby(['Species']).min())

# 2. Tìm giá trị lớn nhất (Max) của từng loài
print("\n--- Giá trị lớn nhất (Max) theo từng loài ---")
print(df_csv.groupby(['Species']).max())

# 3. Tính độ lệch chuẩn (Standard Deviation)
print("\n--- Độ lệch chuẩn (Std) theo từng loài ---")
print(df_csv.groupby(['Species']).std())

--- Giá trị trung bình của từng nhóm Loài (Species) ---
         Weight  Length    Height    Width
Species                                   
Bream     333.0   27.24  12.30316  4.42946
Pike      608.0   41.85  11.12940  5.02230
Roach     135.0   21.50   8.54885  3.20810
--- Số lượng mẫu dữ liệu của mỗi loài ---
Species
Bream    5
Pike     2
Roach    2
Name: Weight, dtype: int64
--- Giá trị nhỏ nhất (Min) theo từng loài ---
         Weight  Length   Height   Width
Species                                 
Bream     242.0    25.4  11.5200  3.8417
Pike      500.0    41.0  10.7388  4.4555
Roach     120.0    21.0   8.1457  3.1234

--- Giá trị lớn nhất (Max) theo từng loài ---
         Weight  Length  Height   Width
Species                                
Bream     430.0    29.0  12.730  5.1340
Pike      716.0    42.7  11.520  5.5891
Roach     150.0    22.0   8.952  3.2928

--- Độ lệch chuẩn (Std) theo từng loài ---
             Weight    Length    Height     Width
Species                    